# Generated by Django 4.0 on 2022-01-20 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('botanical_name', models.CharField(max_length=100, unique=True)),
                ('argument', models.TextField(blank=True, null=True)),
                ('number_of_upvotes', models.IntegerField(default=0)),
                ('upvoters', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
