# Generated by Django 4.0 on 2022-01-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='description',
            new_name='argument',
        ),
    ]
