# Generated by Django 4.0 on 2022-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_rename_description_suggestion_argument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='argument',
            field=models.TextField(blank=True, null=True),
        ),
    ]
