# Generated by Django 4.0 on 2022-01-19 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggestions', '0003_alter_suggestion_argument'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='upvoters',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
