# Generated by Django 4.0 on 2022-02-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0003_suggestion_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='owner',
            new_name='creator',
        ),
    ]
