# Generated by Django 4.0 on 2022-01-12 14:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220106_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='billing_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='billing_street_address1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='users',
            name='billing_street_address2',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='users',
            name='billing_town_or_city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='shipping_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='users',
            name='shipping_street_address1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='users',
            name='shipping_street_address2',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='users',
            name='shipping_town_or_city',
            field=models.CharField(max_length=40),
        ),
    ]
