# Generated by Django 4.0.1 on 2022-01-20 12:58

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('shipping_street_name', models.CharField(max_length=80)),
                ('shipping_street_number', models.CharField(max_length=80)),
                ('shipping_town_or_city', models.CharField(max_length=40)),
                ('shipping_county', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', django_countries.fields.CountryField(max_length=2)),
                ('billing_street_name', models.CharField(max_length=80)),
                ('billing_street_number', models.CharField(max_length=80)),
                ('billing_town_or_city', models.CharField(max_length=40)),
                ('billing_county', models.CharField(blank=True, max_length=80, null=True)),
                ('billing_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', django_countries.fields.CountryField(max_length=2)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('15.75'), max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='checkout.order')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
