# Generated by Django 4.0 on 2022-01-13 15:13

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('shipping_street_name', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_street_number', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('shipping_county', models.CharField(blank=True, max_length=80, null=True)),
                ('shipping_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('billing_street_name', models.CharField(blank=True, max_length=80, null=True)),
                ('billing_street_number', models.CharField(blank=True, max_length=80, null=True)),
                ('billing_town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('billing_county', models.CharField(blank=True, max_length=80, null=True)),
                ('billing_postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('billing_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='checkout.order')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.plant')),
            ],
        ),
    ]
