# Generated by Django 4.0 on 2022-01-14 14:11

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default='Elke', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=django_countries.fields.CountryField(default='Netherlands', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street_name',
            field=models.CharField(default='Paardebloem', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street_number',
            field=models.CharField(default='3', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_town_or_city',
            field=models.CharField(default='Enschede', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=django_countries.fields.CountryField(default='Deutschland', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_street_name',
            field=models.CharField(default='Fairystreet', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_street_number',
            field=models.CharField(default='1', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_town_or_city',
            field=models.CharField(default='Fairyville', max_length=40),
            preserve_default=False,
        ),
    ]
