# Generated by Django 4.0 on 2022-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='elkeharmanny@outlook.com', max_length=80),
            preserve_default=False,
        ),
    ]
