# Generated by Django 4.0 on 2022-01-12 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcart', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
