# Generated by Django 4.0 on 2021-12-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Common_name', models.CharField(max_length=100)),
                ('Botanical_name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=254, null=True)),
                ('Stock', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
