# Generated by Django 4.0 on 2021-12-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='Description',
            field=models.TextField(),
        ),
    ]
