# Generated by Django 4.0 on 2021-12-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='Layer',
            field=models.CharField(choices=[('Large tree', 'Large tree'), ('Small tree', 'Small tree')], default='Large tree', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plant',
            name='Stock',
            field=models.IntegerField(default=0),
        ),
    ]
