# Generated by Django 4.0 on 2021-12-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_layer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Botanical_name',
            new_name='botanical_name',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Common_name',
            new_name='common_name',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Image_url',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='Stock',
            new_name='stock',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='Layer',
        ),
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.category'),
        ),
    ]
